#! /bin/bash
if [ ! -f sink.js/sink.js ];
then
    cd sink.js
    make
    cd ../
fi
juicer merge core/*.js operators/*.js dsp/*.js midi/*.js pattern/*.js scale/*.js tuning/*.js sink.js/*.js teoria/dist/teoria.js -f -s -o audiolet/Audiolet.min.js
